apiVersion: v1
kind: Service
metadata:
  name: snrt-search-service
spec:
  selector:
    app: snrt-search
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8501
  type: LoadBalancer   # NodePort pour cluster local (minikube)
